// <auto-generated />
namespace ASPMVCProjektSklep.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class productDescription : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(productDescription));
        
        string IMigrationMetadata.Id
        {
            get { return "202201312221112_productDescription"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
